version: '3'
services:
  pronuntio:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_IP="0.0.0.0"
      - HTTP_PORT=8080
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER="pr_user"
      - PG_PASS="pr_user_pass"
      - PG_DBNAME="pr_main"
    volumes:
      - db_data:/var/lib/postgresql/data
    depends_on:
      - postgres

  postgres:
    build: scripts/pg/
    ports:
      - "5432:5432"
volumes:
  db_data:
